const data = [
    {
        "id": 1,
        "type": "cake",
        "name": 'Black Cherry',
        "price": 420,
        "inStock" : 10,
        "img" : "https://cdn4.singleinterface.com/files/banner_images/82349/3866_1628076379_BlackCherryCake.png",
    },
    {
        "id": 2,
        "type": "cake",
        "name": 'Red Velvet',
        "price": 400,
        "inStock" : 5,
        "img" : 'https://cdn4.singleinterface.com/files/banner_images/82349/721_1628076428_RedVelvetCake.png',
    },
    {
        "id": 3,
        "type": "cake",
        "name": 'Choco Ivory',
        "price": 420,
        "inStock" : 12,
        "img" : "https://cdn4.singleinterface.com/files/banner_images/82349/5143_1628076389_ChocoIvoryCake.png",
    },
    {
        "id": 4,
        "type": "cake",
        "name": 'Strawberry',
        "price": 420,
        "inStock" : 7,
        "img" : "https://cdn4.singleinterface.com/files/banner_images/82349/70_1628076429_StrawberryCake.png",
    },
    {
        "id": 5,
        "type": "cake",
        "name": 'Alpine Chocolate',
        "price": 420,
        "inStock" : 10,
        "img" : "https://cdn4.singleinterface.com/files/banner_images/82349/7533_1628076378_AlpineChocolateCake.png",
    },
    {
        "id": 6,
        "type": "cake",
        "name": 'Dutch Chocolate',
        "price": 420,
        "inStock" : 10,
        "img" : "https://cdn4.singleinterface.com/files/banner_images/82349/4154_1628076409_DutchChocolateCake.png",
    },
    {
        "id": 7,
        "type": "cake",
        "name": 'Hazelnut',
        "price": 420,
        "inStock" : 10,
        "img" : "https://cdn4.singleinterface.com/files/banner_images/82349/1273_1628076410_HazelnutCake.png",
    },
    {
        "id": 8,
        "type": "cake",
        "name": 'Pineapple',
        "price": 420,
        "inStock" : 10,
        "img" : "https://cdn4.singleinterface.com/files/banner_images/82349/6083_1628076417_PineappleCake.png",
    },
    {
        "id": 9,
        "type": "cake",
        "name": 'Black Forest',
        "price": 420,
        "inStock" : 10,
        "img" : "https://cdn4.singleinterface.com/files/banner_images/82349/3959_1628076379_BlackForestCake.png",
    },
    {
        "id": 10,
        "type": "cake",
        "name": 'Butterscotch Caramello',
        "price": 420,
        "inStock" : 10,
        "img" : "https://cdn4.singleinterface.com/files/banner_images/82349/6738_1628076387_ButterscotchCaramelloCake.png",
    },
    {
        "id": 11,
        "type": "cake",
        "name": 'Midnight Delight',
        "price": 420,
        "inStock" : 10,
        "img" : "https://cdn4.singleinterface.com/files/banner_images/82349/299_1628076418_MidnightDelightCake.png",
    },
    {
        "id": 12,
        "type": "cake",
        "name": 'Shimmer',
        "price": 420,
        "inStock" : 0,
        "img" : "https://cdn4.singleinterface.com/files/banner_images/82349/1514_1628076428_ShimmerCake.png",
    },
    {
        "id": 21,
        "type": "icecream",
        "name": 'Desi Kulfi',
        "price": 100,
        "inStock" : 10,
        "img" : "https://asset-apac.unileversolutions.com/content/dam/unilever/heart/india/pack_shot/8901030838545.01-33714264-png.png.ulenscale.290x290.png",
    },
    {
        "id": 22,
        "type": "icecream",
        "name": 'Uni Cornetto',
        "price": 250,
        "inStock" : 10,
        "img" : "https://asset-apac.unileversolutions.com/content/dam/unilever/heart/global/kw_in/uni_cornetto_thumbnails_product-1862861-png.png.ulenscale.290x290.png",
    },
    
    {
        "id": 23,
        "type": "icecream",
        "name": 'Feast Chocolate',
        "price": 420,
        "inStock" : 0,
        "img" : "https://asset-apac.unileversolutions.com/content/dam/unilever/heart/global/kw_in/chocolate_feast_thumbnails_product-1869482-png.png.ulenscale.290x290.png",
    },
    {
        "id": 24,
        "type": "icecream",
        "name": 'Vanilla',
        "price": 80,
        "inStock" : 10,
        "img" : 'https://asset-apac.unileversolutions.com/content/dam/unilever/heart/global/kw_in/510x510_vanilla-1868094-png.png.ulenscale.290x290.png',
    },
    {
        "id": 25,
        "type": "icecream",
        "name": 'Gems Cup',
        "price": 100,
        "inStock" : 10,
        "img" : "https://asset-apac.unileversolutions.com/content/dam/unilever/heart/global/kw_in/gems_thumbnails_product-1862846-png.png.ulenscale.290x290.png",
    },
    
    {
        "id": 26,
        "type": "icecream",
        "name": 'Choco Vanilla Cornetto',
        "price": 420,
        "inStock" : 10,
        "img" : "https://asset-apac.unileversolutions.com/content/dam/unilever/heart/global/kw_in/choco_vanilla_thumbnails_product-1862862-png.png.ulenscale.290x290.png",
    },
    {
        "id": 27,
        "type": "icecream",
        "name": 'Strawberry',
        "price": 120,
        "inStock" : 10,
        "img" : "https://asset-apac.unileversolutions.com/content/dam/unilever/heart/global/kw_in/510x510_strawberry-1868113-png.png.ulenscale.290x290.png",
    },
    
    {
        "id": 28,
        "type": "icecream",
        "name": 'Disk Oreo Caramello',
        "price": 420,
        "inStock" : 10,
        "img" : "https://asset-apac.unileversolutions.com/content/dam/unilever/heart/global/kw_in/oreo_thumbnails_product-1862856-png.png.ulenscale.290x290.png",
    },
    {
        "id": 29,
        "type": "icecream",
        "name": 'Fruit and Nut',
        "price": 200,
        "inStock" : 10,
        "img" : "https://asset-apac.unileversolutions.com/content/dam/unilever/heart/global/kw_in/510x510_fruit_n_nut-1868173-png.png.ulenscale.290x290.png",
    },
    {
        "id": 30,
        "type": "icecream",
        "name": 'Mini Butterscotch',
        "price": 220,
        "inStock" : 10,
        "img" : "https://asset-apac.unileversolutions.com/content/dam/unilever/heart/global/kw_in/butterscotch_mini_thumbnails_product-1862829-png.png.ulenscale.290x290.png",
    },
    {
        "id": 31,
        "type": "icecream",
        "name": 'Divine Chocolate',
        "price": 150,
        "inStock" : 10,
        "img" : "https://asset-apac.unileversolutions.com/content/dam/unilever/heart/global/kw_in/510x510_chocolate-1868175-png.png.ulenscale.290x290.png",
    },
    {
        "id": 32,
        "type": "icecream",
        "name": 'Butterscotch',
        "price": 90,
        "inStock" : 10,
        "img" : "https://asset-apac.unileversolutions.com/content/dam/unilever/heart/global/kw_in/1_layer_butterscotch_kwallity_walls_cup_510px-1868049-png.png.ulenscale.290x290.png",
    },
]

export default data;